
name: Build and Deploy auth service to GKE

on:
  push:
    paths:
        - auth_service/**
  workflow_dispatch:

env:
  PROJECT_ID: solveit-369711
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  GAR_LOCATION: europe-west4
  GKE_CLUSTER: solveit-369711-gke
  GKE_ZONE: europe-west4
  REPOSITORY: services-repository
  AUTH_SERVICE_IMAGE: auth_service
  AUTH_DB_USER: ${{ secrets.AUTH_DB_USER }}
  AUTH_DB_PASS: ${{ secrets.AUTH_DB_PASS }}
  AUTH_ADMIN_USER: ${{ secrets.AUTH_ADMIN_USER }}
  AUTH_ADMIN_PASS: ${{ secrets.AUTH_ADMIN_PASS }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Patch auth service variables
      run: |-
        sed "s/POSTGRES_USER[^\"]*/POSTGRES_USER=${AUTH_DB_USER}/" auth_service/.env | tee auth_service/.env
        sed "s/POSTGRES_PASSWORD[^\"]*/POSTGRES_PASSWORD=${AUTH_DB_PASS}/" auth_service/.env | tee auth_service/.env
        sed "s/DEFAULT_ADMIN_USERNAME[^\"]*/DEFAULT_ADMIN_USERNAME=${AUTH_ADMIN_USER}/" auth_service/.env | tee auth_service/.env
        sed "s/DEFAULT_ADMIN_PASSWORD[^\"]*/DEFAULT_ADMIN_PASSWORD=${AUTH_ADMIN_PASS}/" auth_service/.env | tee auth_service/.env

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./auth_service

    - name: Helper
      run: |
       gcloud auth configure-docker -q

    - name: Delete old image in GCR
      run: |
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE || true

    - name: Push to GCR
      run: |-
       docker push eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE



    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        envsubst < kubernetes/authservice.yaml | kubectl apply -f -
        kubectl rollout status deployment/auth-service-deployment
