name: EXTRA | Build and Deploy to GKE

on:
  workflow_dispatch:
  push:
    branches: [ "deploy" ]

env:
  PROJECT_ID: testdev-372012
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_EXTRA }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_EXTRA }}
  GAR_LOCATION: europe-west4
  GKE_CLUSTER: testdev-372012-gke
  GKE_ZONE: europe-west4
  REPOSITORY: services-repository
  JOB_SERVICE_DB_IMAGE: jobservice_db
  JOB_SERVICE_IMAGE: jobservice
  FRONTEND_IMAGE: frontend
  AUTH_SERVICE_DB_IMAGE: auth_service_database
  AUTH_SERVICE_IMAGE: auth_service
  FS_SERVICE_IMAGE: fs_service
  JOB_DB_USER: ${{ secrets.JOB_DB_USER }}
  JOB_DB_PASS: ${{ secrets.JOB_DB_PASS }}
  SOLVER_DB_USER: ${{ secrets.SOLVER_DB_USER }}
  SOLVER_DB_PASS: ${{ secrets.SOLVER_DB_PASS }}
  FS_DB_USER: ${{ secrets.FS_DB_USER }}
  FS_DB_PASS: ${{ secrets.FS_DB_PASS }}
  AUTH_DB_USER: ${{ secrets.AUTH_DB_USER }}
  AUTH_DB_PASS: ${{ secrets.AUTH_DB_PASS }}
  AUTH_ADMIN_USER: ${{ secrets.AUTH_ADMIN_USER }}
  AUTH_ADMIN_PASS: ${{ secrets.AUTH_ADMIN_PASS }}


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Patch auth service variables
      run: |-
        sed -i "s/POSTGRES_USER[^\"]*/POSTGRES_USER=${AUTH_DB_USER}/" ./auth_service/.env
        sed -i "s/POSTGRES_PASSWORD[^\"]*/POSTGRES_PASSWORD=${AUTH_DB_PASS}/" ./auth_service/.env
        sed -i "s/DEFAULT_ADMIN_USERNAME[^\"]*/DEFAULT_ADMIN_USERNAME=${AUTH_ADMIN_USER}/" ./auth_service/.env
        sed -i "s/DEFAULT_ADMIN_PASSWORD[^\"]*/DEFAULT_ADMIN_PASSWORD=${AUTH_ADMIN_PASS}/" ./auth_service/.env

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_DB_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./auth_service/database
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./auth_service
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_DB_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_JOBSERVICE }} \
          ./job_service/db
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_JOBSERVICE }} \
          ./job_service
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./filestorage/service
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$FRONTEND_IMAGE" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./frontend

    - name: Helper
      run: |
       gcloud auth configure-docker -q

    - name: Delete old image in GCR
      run: |
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_DB_IMAGE || true
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE || true
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_DB_IMAGE || true
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_IMAGE || true
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE || true
       gcloud container images delete eu.gcr.io/$PROJECT_ID/$FRONTEND_IMAGE || true

    - name: Push to GCR
      run: |-
       docker push eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_DB_IMAGE
       docker push eu.gcr.io/$PROJECT_ID/$AUTH_SERVICE_IMAGE
       docker push eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_DB_IMAGE
       docker push eu.gcr.io/$PROJECT_ID/$JOB_SERVICE_IMAGE
       docker push eu.gcr.io/$PROJECT_ID/$FS_SERVICE_IMAGE
       docker push eu.gcr.io/$PROJECT_ID/$FRONTEND_IMAGE



    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        envsubst < kubernetes/authservice.yaml | kubectl apply -f -
        envsubst < kubernetes/jobservice.yaml | kubectl apply -f -
        envsubst < filestorage/DB/postgres-deployment.yaml | kubectl apply -f -
        envsubst < filestorage/fs-deployment.yaml | kubectl apply -f -
        kubectl rollout status deployment/auth-database
        kubectl rollout status deployment/auth-service-deployment
        kubectl rollout status deployment/postgres
        kubectl rollout status deployment/jobservice-deployment
        kubectl rollout status deployment/fs-postgres
        kubectl rollout status deployment/fs-service
        kubectl rollout status deployment/frontend-deployment
        kubectl get services -o wide
